In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor


In [42]:
df = pd.read_csv('train.csv')
X= df.drop(["SalePrice"],axis=1)

In [43]:
y = df["SalePrice"].as_matrix()
y

array([ 208500.,  181500.,  223500., ...,  266500.,  142125.,  147500.])

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 666)

In [45]:
forest = RandomForestRegressor()
forest.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [46]:
# 予測値を計算
y_train_pred = forest.predict(X_train)
y_test_pred = forest.predict(X_test)
# MSEの計算
from sklearn.metrics import mean_squared_error
print('MSE train : %.3f, test : %.3f' % (mean_squared_error(y_train, y_train_pred), mean_squared_error(y_test, y_test_pred)) )
# R^2の計算
from sklearn.metrics import r2_score
print('MSE train : %.3f, test : %.3f' % (r2_score(y_train, y_train_pred), r2_score(y_test, y_test_pred)) )

MSE train : 155649915.758, test : 1234682291.154
MSE train : 0.976, test : 0.779


In [47]:
df2 = pd.read_csv('test.csv')

In [48]:
X2= df2

In [49]:
y2 = forest.predict(X2)

In [50]:
y2

array([ 128785.,  146180.,  173700., ...,  160655.,  124200.,  214550.])

In [51]:
a =[i for i in range(1461,2920)]
dfnew = pd.DataFrame({'SalePrice':y2,'Id': a})

In [63]:
# 必要なライブラリのインポート
from sklearn.model_selection import GridSearchCV
# 動かすパラメータを明示的に表示、今回は決定木の数を変えてみる
params = {'n_estimators'  : [1000], 'n_jobs': [-1]}


In [64]:
# モデルにインスタンス生成
mod = RandomForestRegressor()
# ハイパーパラメータ探索
cv = GridSearchCV(mod, params, cv = 10, n_jobs =1)
cv.fit(X_train, y_train)

GridSearchCV(cv=10, error_score='raise',
       estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'n_estimators': [1000], 'n_jobs': [-1]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [65]:
cv.best_params_

{'n_estimators': 1000, 'n_jobs': -1}

In [66]:
cv.best_score_

0.85312848369423944

In [67]:
cv.score(X_test, y_test)

0.79314020876815428

In [68]:
mod.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [72]:
# 予測値を計算
y_train_pred = mod.predict(X_train)
y_test_pred = mod.predict(X_test)
# MSEの計算
from sklearn.metrics import mean_squared_error
print('MSE train : %.3f, test : %.3f' % (mean_squared_error(y_train, y_train_pred), mean_squared_error(y_test, y_test_pred)) )
# R^2の計算
from sklearn.metrics import r2_score
print('MSE train : %.3f, test : %.3f' % (r2_score(y_train, y_train_pred), r2_score(y_test, y_test_pred)) )

MSE train : 158071251.277, test : 1331094762.607
MSE train : 0.976, test : 0.762


In [74]:
y3 = mod.predict(X2)

In [75]:
y3

array([ 115970.,  134995.,  176370., ...,  159830.,  112760.,  225430.])

In [77]:
a =[i for i in range(1461,2920)]
dfnew1 = pd.DataFrame({'SalePrice':y3,'Id': a})

In [78]:
dfnew1.to_csv("pred3.csv")

In [80]:
from sklearn.ensemble import GradientBoostingRegressor
gbct = GradientBoostingRegressor(random_state=0, max_depth=3, learning_rate=0.1)
gbct.fit(X_train, y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='ls', max_depth=3, max_features=None,
             max_leaf_nodes=None, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=100, presort='auto', random_state=0,
             subsample=1.0, verbose=0, warm_start=False)

In [84]:
y_train_pred = gbct.predict(X_train)
y_test_pred = gbct.predict(X_test)
# MSEの計算
from sklearn.metrics import mean_squared_error
print('MSE train : %.3f, test : %.3f' % (mean_squared_error(y_train, y_train_pred), mean_squared_error(y_test, y_test_pred)) )
# R^2の計算
from sklearn.metrics import r2_score
print('MSE train : %.3f, test : %.3f' % (r2_score(y_train, y_train_pred), r2_score(y_test, y_test_pred)) )

MSE train : 254444255.992, test : 1094915114.148
MSE train : 0.962, test : 0.804


In [87]:
y4 = gbct.predict(X2)

In [88]:
a =[i for i in range(1461,2920)]
dfnew1 = pd.DataFrame({'SalePrice':y4,'Id': a})
dfnew1.to_csv("pred4.csv")